### ISSUE TITLE
Release version

### ISSUE THREAD

**Issue by fredatgithub** [dbelmont/ExpressionBuilder#1]
hello,
A release version or a screenshot would be nice to see your app.

**Comment by dbelmont** [comment]
Hi,
Thank you for the tip. I am new at GitHub.
I made this application just to support an article that I wrote, but I will do as you suggested.

**Comment by fredatgithub** [comment]
ok thanks

**Comment by fredatgithub** [comment]
I have forked your version and created a release
https://github.com/fredatgithub/ExpressionBuilder/releases/tag/v1.0
