### ISSUE TITLE
IQueryable

### ISSUE THREAD

**Issue by eveneveneven** [dbelmont/ExpressionBuilder#12]
Greetings David, I like your work - however I can't make it work with LINQ to SQL.

Am I doing this wrong, or is there there anything we can do to make it compatible with IQueryable?

Best regards,
Even

**Comment by dbelmont** [comment]
Hi Even,

First of all, thanks for your interest in the project.

I never tested this code with LINQ to SQL. In fact, I admit there are a lot of things that I'd like to improve in this project, but just can't find the time to do so. Actually, I've got a few improvements on the way to be released soon, I'll check your issue and try to release a fix for it along with the other stuff. I just can't give you a precise date, but it shouldn't take long (like, still this year... 😄).

By the way, many thanks for logging this issue. This kind of feedback helps me a lot.

Kind regards,
David

**Comment by eveneveneven** [comment]
Thanks for the quick response! I think I got your back on this "issue". I've tested it and it seems to work just as expected.

Submitted a pull request :)

**Comment by dbelmont** [comment]
Many thanks for your contribution, Even.

Actually, that change was already covered in the next version, which I expect to release this November. I'm only finishing one last feature that I'd like to add to this release.

Once again, thank you very much.

Cheers.

**Comment by gekakud** [comment]
Hi David. Great library! It is going to save me a lot of time, but mainly provide fluent readable API. Waiting for your next release to test it in EF Linq to SQL. Keep going))

**Comment by eveneveneven** [comment]
@gekakud Check the closed pull requests if you want to test Linq to SQL before David gets the time to publish the next release. He had already made this change in his code.

I'm also eagerly waiting the next release 👍

**Comment by gekakud** [comment]
@eveneveneven Sure I will! Thank you guys

**Comment by dbelmont** [comment]
Hi Even,

I uploaded a release candidate version on NuGet today. It has the implicit cast from `Filter<T>` to `Expression<Func<T, bool>>` and I've added some tests using LINQ to SQL as well (just in case...).

If you add the reference through the ***"Manage NuGet packages"*** option in Visual Studio, don't forget to tick the ***"Include prerelease"*** option (otherwise, this version won't be listed).

Many thanks,
David

**Comment by eveneveneven** [comment]
Thanks David, working as expected!
