### ISSUE TITLE
Change `Expression.Property` to `Expression.PropertyOrField`. ERROR: Instance property '<FIELD>' is not defined for type '<CLASS>'

### ISSUE THREAD

**Issue by glenn2223** [dbelmont/ExpressionBuilder#14]
**I'm using LINQ TO SQL `IEnumerable`**

I'm getting the following exception. 
`Instance property 'AssignedTo' is not defined for type 'IssueSearch'`
It was only starting to get thrown after adding this custom `IssueSearch` class with the embedded `UserInfo`.

Here's my class
```C#
public class IssueSearch
{
    //<My Other Variables>
    public UserInfo AssignedTo; // <-- The Important One
}

public class UserInfo
{
    public string Id; // <-- The Important One
    //<My Other Variables>
}
```

Here's my `Filter<IssueSearch>.By`. (I've included the `Type`'s, for reference)
```C#
Filter.By(
    "AssignedTo.Id", // string
    Operation.In, // ExpressionBuilder.Common.Operation
    [ "Id1", "Id2" ], //  object {System.Collections.Generic.List<object>}
    null, // object
    FilterStatementConnector.And); // ExpressionBuilder.Common.FilterStatementConnector

```

This is how I populate the `IEnumerable<IssueSearch>` using `LINQ TO SQL`
```C#
var query =
    (
        from i in d.Issues
        from aT in d.Users
            .Where(x => i.AssignedTo == x.Id)
            .DefaultIfEmpty()
         select new IssueSearch
         {
            //<My Other Variables>
            AssignedTo = new UserInfo
            {
                Id = aT.Id
                //<My Other Variables>
             }
        }
    )
    .Where(``Filter``); // <-- Here I Drop The Filter And The Exeption Is Thrown
```

**Stack Trace:**
at System.Linq.Expressions.Expression.Property(Expression expression, String propertyName)
at ExpressionBuilder.Helpers.BuilderHelper.GetMemberExpression(Expression param, String propertyName)
at ExpressionBuilder.Builders.FilterBuilder.GetExpression(ParameterExpression param, IFilterStatement statement, String propertyName)
at ExpressionBuilder.Builders.FilterBuilder.GetExpression[T](IFilter filter)
at ExpressionBuilder.Generics.Filter\`1.op_Implicit(Filter\`1 filter)
<br/>

**Just a bit of background (FYI):**
I've built a master page that I can override Field values, pass Classes too, etc. etc.. 
This way I can use the same master page, make some small changes to the child page, then I have a new page that has search functionality for a set DB table.

_Also, sorry if this isn't the right way of querying the issue_

**Comment by glenn2223** [comment]
Just an addition. Changing the `.Where()` to the below code does work.

```C#
.Where( x => new string[] { "Id1", "Id2" }.Contains(x.AssignedTo.Id))
```

**Comment by dbelmont** [comment]
Hi Glenn,

Many thanks for taking the time to log this issue. Feedback is always welcome! :)

Now, regarding the issue, it's a bit strange because (from what you've described) it should be working. I'm pretty sure we got unit tests for this specific case.

I'm about to release a new version within the next days and it'll fix a bug around the usage of the library with LINQ To SQL. It doesn't seem to be exactly your case, but I'd be really glad if you could check if this issue still happens in the new version. In this meanwhile, I'll be investigating it.

Many thanks,
David

**Comment by eveneveneven** [comment]
@glenn2223 Might it be that in this case, when you are using ExpressionBuilder it will execute the sql before the .Where(Filter) is run. In that case it could be very much related to my issue which should be addressed soon.

What I'm trying to say is, if you run the .Where(x => new string[] { "Id1", "Id2" }.Contains(x.AssignedTo.Id)) on an IQueryable it will include the UserInfo entity for you. But in this case you might have to add .Include("UserInfo") to the query before .Where(Filter).
Am I off the mark here? Just my thoughts :)

**Comment by glenn2223** [comment]
@eveneveneven. I see where you're coming from.

I tried adding `.Include("UserInfo")` and no luck. Same exception. I'll wait for the updated version and report back.

**Comment by eveneveneven** [comment]
Worth a shot. 
Anyway when I look at it should probably be .Include("AssignedTo") or .Include(is => is.AssignedTo) and be before whenever the query is enumerated so that the include will be included in the sql.

But seeing that you already get an IEnumerable<IssueSearch> from your code it may not be relevant anyway.

I'm just trying to be helpful and learn something at the same time!

**Comment by glenn2223** [comment]
@eveneveneven. For the sake of learning 😁

I tried both your other include suggestions and no luck 😞

**Comment by dbelmont** [comment]
Hi Glenn,

I uploaded a release candidate version on NuGet today. Would you mind trying again with that version when you get some time?

If you add the reference through the ***"Manage NuGet packages"*** option in Visual Studio, don't forget to tick the ***"Include prerelease"*** option (otherwise, this version won't be listed).

Many thanks,
David

**Comment by glenn2223** [comment]
No luck. 😭

The only thing I can think of is that I'm doing something wrong. Does the below Filter look like it's supposed to against a model you use (that works)?

![image](https://user-images.githubusercontent.com/33450392/33661577-71131f04-da80-11e7-8066-42934298ae76.png)

Do you know of a way that I can debug through your .dll from within Visual Studio to ensure the correct method is being called and that it's building the expression correctly?? (Not Googled it yet)

**Comment by glenn2223** [comment]
Just wanted to make sure that the way I was building the `Filter<>` wasn't the problem and that it wasn't the class field. Just hardcoded a filter using a `long` field named "Id".

The below code returned the same exception
 `Instance property 'Id' is not defined for type 'IssueSearch'`

```c#
var f = new Filter<IssueSearch>();
f.By("Id", Operation.EqualTo, 1L, connector: FilterStatementConnector.And);
```

Just not sure what I could be doing wrong.

Thanks for all your help BTW guys

**Comment by eveneveneven** [comment]
@glenn2223 If you could provide some "working" code I'd be happy to have a look at it.

**Comment by glenn2223** [comment]
@eveneveneven Sorry, I mean against the model David uses in the GitHub example project. No matter what I try I can't seem to get a LINQ to SQL query to work.

I managed to launch the window forms project from the example. 

The only difference I can see is that my `Statement` is a `List<IFilterStatement>[]` (an Array of List of IFilterStatement's) rather than `IFilerStatement[]` (an array of IFilterStatement's). See images below for ref.
 
Surely this isn't the problem?? But it's the only difference I can see.

**_p.s. I know the image from my solution references `TaskSearch` instead of `IssueSearch`, just ignore that I copied it from the wrong file (my bad)_**

Image from the solution included with the GitHub Download
![image](https://user-images.githubusercontent.com/33450392/33724328-1073f870-db67-11e7-802c-3ccbbf105f91.png)

Image from my solution
![image](https://user-images.githubusercontent.com/33450392/33724610-ce5f1afe-db67-11e7-94b9-49c24c461a82.png)

**Comment by glenn2223** [comment]
OMFG <- Pardon my French

After some more digging, I found the problem. I'm not going to tell you straight away though. First, I shall explain.

I saw the problem was with `System.Linq.Expressions.Expression.Property(Expression expression, String propertyName)`. So I pulled up the method on Microsoft's Dev Network, [here](https://msdn.microsoft.com/en-us/library/bb341554%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396).

I then placed my class, field etc. straight into that function... threw the same exception. Hmmm...

I thought, just for giggles, lets place their code in my solution. Just to make sure. Success! So, Microsoft hasn't screwed me over. Back to, hmmm...

I then saw something, the method is called `Expression.Property` and their class consists of;
``` CSharp
public int sample {get; set;}
```

Looked back at mine... WAIT A SECOND... OMFG. Mine is a `field`!!!!
Changed my testing method to `Expression.Field` and Success (well, partial success anyway).

**_Will you be adding support for `Expression.Field`?_**
You can change it to `Expression.PropertyOrField`[[LINK]](https://msdn.microsoft.com/en-us/library/system.linq.expressions.expression.propertyorfield%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396), or you can see if you can detect it (although this seems pointless to me)

_________________________

I now have a new exception, grrr...

**Message:**
```
Expression of type 'System.Object[]' cannot be used for parameter of type 'System.String' of method 'Boolean Contains(System.String)'
```
**Stack Trace:**
``` CSharp
at System.Linq.Expressions.Expression.ValidateOneArgument(MethodBase method, ExpressionType nodeKind, Expression arg, ParameterInfo pi)
at System.Linq.Expressions.Expression.ValidateArgumentTypes(MethodBase method, ExpressionType nodeKind, ReadOnlyCollection`1& arguments)
```

I can see the problem, however I use: 
```CSharp
public static object ChangeType(object value, Type conversionType);
``` 
and (as you can see) this returns an `object`. Any help??
