### ISSUE TITLE
How to compile ?

### ISSUE THREAD

**Issue by clabnet** [dbelmont/ExpressionBuilder#15]
I have VS2015, .net 4 until 4.71, 
what .NET framework must use to compile ?

**Comment by dbelmont** [comment]
Hi Claudio,

Unfortunately, the last release was built using some features only available on C# 7, but I've already fixed it and it will be in the next release (that should be available in a few days). In this meanwhile, you can check out the branch [v1.1.2](https://github.com/dbelmont/ExpressionBuilder/tree/v1.1.2) (which is the next release branch).

Many thanks for your interest in the project and sorry for the late reply.

Cheers,
David
