### ISSUE TITLE
Add ability to include non generic usage

### ISSUE THREAD

**Issue by radenkozec** [dbelmont/ExpressionBuilder#25]
For me is the problem to provide generic type like this:
`var filter = new Filter<Person>();`
What I need is:
```
var type = Type.GetType("Bla." + mappedEntityTableName + "RecievedLog");
var filter = new Filter(type);

```
Can you provide this version?

**Comment by dbelmont** [comment]
Hi @radenkozec,
Sorry for the late reply. I'll have a look at this.
I'll let you know when it's available.
Cheers.

**Comment by dbelmont** [comment]
Hi @radenkozec,

I created a new class called `FilterFactory` to enable the creation of filters without using generics. Something like this:
```CSharp
var filter = FilterFactory.Create(typeof(Person));
```
I added this to a [pre-release package at NuGet.org](https://www.nuget.org/packages/LambdaExpressionBuilder/2.0.2-beta). Would you mind checking that out and letting me know what you think about it?

Many thanks,
David

**Comment by radenkozec** [comment]
@dbelmont Thanks for your effort. I managed to solve this in some other way. To be honest I don't remember how. Probably not using your library. Hopefully someone will find this feature useful.
