### ISSUE TITLE
Convert "Filter" to Native .NET Expression.Lambda

### ISSUE THREAD

**Issue by lousadacbc** [dbelmont/ExpressionBuilder#34]
Hello everyone,

I would like to use this nuget, it's very good. But I did not want my data layer to depend directly on it. Is there any way to do a caste or convert "Filter" to Native .NET Expression.Lambda?

Thank you

**Comment by dbelmont** [comment]
Hi @lousadacbc,
Many thanks for using the project! 😄 Sorry for the late reply.
You can actually implicitly convert it to `Expression<Func<TClass, bool>>` by doing something like this:
```CSharp
var filter = new Filter<Person>();
//...
var expr = (Expression<Func<Person, bool>>)filter;
```
