### ISSUE TITLE
NETSTANDARD2_2

### ISSUE THREAD

**Issue by ppmll** [dbelmont/ExpressionBuilder#45]
I am using dotnet 2.2 and was trying your library, I realized that your code is not completelly prepared for netstandard 2.2 but the change is not that hard.

What I did to make it work was:
1. in Settings.cs changed the:
    #if NETSTANDARD2_0
to 
    #if (NETSTANDARD2_0 || NETSTANDARD2_1 || NETSTANDARD2_2)

2. in the Contains and NotContains operation, changed
     private readonly MethodInfo stringContainsMethod = typeof(string).GetMethod("Contains");
to 
     private readonly MethodInfo stringContainsMethod = typeof(string).GetMethod("Contains", new Type[] { typeof(string) });

After that, I ran all your test cases and all went fine in both versions of net standard.

Hope this helps someone in the future!

**Comment by dbelmont** [comment]
Hi @ppmll,

That's amazing! 😄🎉👏 Many thanks for that!

Would you mind creating a pull request with this fix? That would help lots of people.

And, once again, many thanks!

Cheers,
David
