### ISSUE TITLE
Filter.By with many-to-many relationship

### ISSUE THREAD

**Issue by NickSevens** [dbelmont/ExpressionBuilder#51]
Hi David, really like this library, but I have an issue with filtering in a many-to-many EF core setup.
I have some models like:

```csharp
class SecureObject {
  IEnumerable<Membership> Membership { get; set; }
}

class Membership {
  SecureObject SecureObject { get; set; }
  User User { get; set; }
  MembershipType MembershipType { get; set; }
}

class User {
  string DisplayName { get; set; }
}
```

I'm trying to dynamically filter a db query of SecureObjects by user's display name (among other things).

Is there any way to pass in this query? Can't get it to work right now, but this is what I tried:
`filter.By(Membership.User.DisplayName, ...)` resulting in:
> System.ArgumentException: ''User' is not a member of type 'System.Collections.Generic.ICollection`1[....Model.Membership]''

Any help would be greatly appreciated!

**Comment by NickSevens** [comment]
@dbelmont any chance you could help out? :)

**Comment by aldrashan** [comment]
We only filter 2 levels deep and the syntax there is ` filter.By("ArrayName[PropertyOfArrayObjectName]", ...);`. So in your case it might be `"Membership[User][DisplayName]"` or `"Membership[User].DisplayName"`?

EDIT
After working with the source code and looking at the tests the correct syntax is: `"Membership[User.DisplayName]"`.
