### ISSUE TITLE
DateTimeOffset not working

### ISSUE THREAD

**Issue by pauldeen79** [dbelmont/ExpressionBuilder#8]
When I try to filter on a property that is of type DateTimeOffset, then I get an exception that says the type is not supported. DateTime is working, though.

Is it possible to support DateTimeOffset also?

**Comment by dbelmont** [comment]
Hi Paul,
I'm working on an update to create a configuration section to enable support to other types. You'll be able to map a type to a type group (used to define the supported operations), what will enable you to have support not only to `DateTimeOffset` but to basically any other type.
I already finished it, but I still need to test it a bit more and write some documentation on how to use it. I'll let you know as soon as it's released.
Many thanks for your help! 😃
Cheers.

**Comment by dbelmont** [comment]
This issue was fixed in [version 1.1.1](https://github.com/dbelmont/ExpressionBuilder/releases/tag/v1.1.1).
